# Copyright 2025 Rainer Gerhards and Others
#
# https://github.com/rsyslog/rsyslog
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: elasticsearch-8-tests

on:
  pull_request:
    paths:
      - 'tests/es-*.sh'
      - 'tests/diag.sh'
      - '.github/workflows/elasticsearch-tests.yml'
      - 'plugins/omelasticsearch/**'

jobs:
  elasticsearch:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      RSYSLOG_TESTBENCH_EXTERNAL_ES_URL: http://127.0.0.1:19200
      ES_HOST: 127.0.0.1
      ES_PORT: 19200
      DOCKER_RUN_EXTRA_OPTS: --network host
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        env:
          discovery.type: single-node
          xpack.security.enabled: "false"
          ES_JAVA_OPTS: -Xms1g -Xmx1g
        ports:
          - 19200:9200
        options: >-
          --health-cmd="curl --fail http://localhost:9200/_cluster/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: run elasticsearch test matrix
        env:
          RSYSLOG_DEV_CONTAINER: rsyslog/rsyslog_dev_base_ubuntu:22.04
          RSYSLOG_CONFIGURE_OPTIONS_OVERRIDE: >-
            --enable-testbench --enable-omstdout --enable-imdiag --enable-impstats
            --disable-imfile --disable-imfile-tests --disable-fmhttp --enable-valgrind
            --disable-default-tests --disable-imtcp-tests --enable-elasticsearch-tests
            --enable-elasticsearch
          CI_MAKE_OPT: -j20
          CI_MAKE_CHECK_OPT: -j8
          CI_CHECK_CMD: check
          ABORT_ALL_ON_TEST_FAIL: 'NO'
          CI_VALGRIND_SUPPRESSIONS: ubuntu22.04.supp
          RSYSLOG_STATSURL: http://build.rsyslog.com/testbench-failedtest.php
          USE_AUTO_DEBUG: 'off'
          VERBOSE: '1'
        run: |
          chmod -R go+rw .
          devtools/devcontainer.sh --rm devtools/run-ci.sh

      - name: show error logs (if we errored)
        if: ${{ failure() || cancelled() }}
        run: |
          devtools/gather-check-logs.sh
          cat failed-tests.log
